/**
 * Mock data — Dòng họ Nguyễn Duy — Làng Nghìn, An Bài, Quỳnh Phụ, Thái Bình
 * Generated from Gia_Pha_Nguyen_Duy_Supabase.csv
 * 123 thành viên, 16 thế hệ
 */
import type { TreeNode, TreeFamily } from './tree-layout';

export const MOCK_PEOPLE: TreeNode[] = [
    // ═══ Đời 1 ═══
    { id: 'D01-001', displayName: 'Nguyễn Duy Hòa', gender: 1, generation: 1, birthYear: 1496, deathYear: 1577, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F001'], parentFamilyIds: [] },
    { id: 'S_D01-001', displayName: 'Nghiêm Quý Thị', gender: 2, generation: 1, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 2 ═══
    { id: 'D02-001', displayName: 'Nguyễn Duy Riễn', gender: 1, generation: 2, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F001'] },
    { id: 'D02-002', displayName: 'Nguyễn Duy Tân', gender: 1, generation: 2, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F001'] },
    { id: 'D02-003', displayName: 'Nguyễn Duy Trạch', gender: 1, generation: 2, birthYear: 1524, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F002'], parentFamilyIds: ['F001'] },
    // ═══ Đời 3 ═══
    { id: 'D03-001', displayName: 'Nguyễn Duy Hộ', gender: 1, generation: 3, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F003'], parentFamilyIds: ['F002'] },
    { id: 'S_D03-001', displayName: 'Đỗ Thị Chung', gender: 2, generation: 3, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 4 ═══
    { id: 'D04-001', displayName: 'Nguyễn Duy Khối', gender: 1, generation: 4, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F004'], parentFamilyIds: ['F003'] },
    // ═══ Đời 5 ═══
    { id: 'D05-001', displayName: 'Nguyễn Duy Điển', gender: 1, generation: 5, birthYear: 1672, deathYear: 1711, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F005'], parentFamilyIds: ['F004'] },
    { id: 'S_D05-001', displayName: 'Ngụy Thị Trong', gender: 2, generation: 5, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 6 ═══
    { id: 'D06-001', displayName: 'Nguyễn Duy Roãn', gender: 1, generation: 6, birthYear: 1708, deathYear: 1775, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F006'], parentFamilyIds: ['F005'] },
    { id: 'D06-002', displayName: 'Nguyễn Duy Cúc', gender: 1, generation: 6, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F005'] },
    { id: 'D06-003', displayName: 'Nguyễn Duy (Quế Vũ)', gender: 1, generation: 6, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F005'] },
    { id: 'S_D06-001', displayName: 'Vũ Thị Hòa', gender: 2, generation: 6, birthYear: 1706, deathYear: 1781, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 7 ═══
    { id: 'D07-001', displayName: 'Nguyễn Duy Vẽ', gender: 1, generation: 7, birthYear: 1723, deathYear: 1788, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F007'], parentFamilyIds: ['F006'] },
    { id: 'S_D07-001', displayName: 'Vũ Thị Phao', gender: 2, generation: 7, birthYear: 1734, deathYear: 1794, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 8 ═══
    { id: 'D08-001', displayName: 'Nguyễn Duy Hoán', gender: 1, generation: 8, birthYear: 1759, deathYear: 1821, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F008'], parentFamilyIds: ['F007'] },
    { id: 'D08-002', displayName: 'Nguyễn Duy Đầm', gender: 1, generation: 8, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F007'] },
    { id: 'S_D08-001', displayName: 'Vũ Thị Doan', gender: 2, generation: 8, birthYear: 1774, deathYear: 1835, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 9 ═══
    { id: 'D09-001', displayName: 'Nguyễn Duy Bang', gender: 1, generation: 9, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F008'] },
    { id: 'D09-002', displayName: 'Nguyễn Duy Nham', gender: 1, generation: 9, birthYear: 1795, deathYear: 1862, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F009'], parentFamilyIds: ['F008'] },
    { id: 'D09-003', displayName: 'Nguyễn Duy Quý', gender: 1, generation: 9, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F008'] },
    { id: 'S_D09-002', displayName: 'họ Đặng', gender: 2, generation: 9, birthYear: 1794, deathYear: 1862, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 10 ═══
    { id: 'D10-001', displayName: 'Nguyễn Duy Trinh', gender: 1, generation: 10, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F009'] },
    { id: 'D10-002', displayName: 'Nguyễn Duy Khanh', gender: 1, generation: 10, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F009'] },
    { id: 'D10-003', displayName: 'Nguyễn Duy Khoan Giản', gender: 1, generation: 10, birthYear: 1832, deathYear: 1868, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F010'], parentFamilyIds: ['F009'] },
    { id: 'S_D10-003', displayName: 'Trần Thị', gender: 2, generation: 10, birthYear: 1830, deathYear: 1894, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 11 ═══
    { id: 'D10-004', displayName: 'Nguyễn Thị Ngọc', gender: 2, generation: 11, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F010'] },
    { id: 'D11-001', displayName: 'Nguyễn Duy Khâm', gender: 1, generation: 11, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F011'], parentFamilyIds: ['F010'] },
    { id: 'D11-002', displayName: 'Nguyễn Duy Sảng', gender: 1, generation: 11, birthYear: 1856, deathYear: 1921, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F012'], parentFamilyIds: ['F010'] },
    { id: 'S_D11-001', displayName: 'Nguyễn Thị Viễn', gender: 2, generation: 11, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D11-002', displayName: 'Phạm Thị Lượt', gender: 2, generation: 11, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 12 ═══
    { id: 'D12-T01', displayName: 'Nguyễn Duy Tồm', gender: 1, generation: 12, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F011'] },
    { id: 'D11-G01', displayName: 'Nguyễn Thị Dược', gender: 2, generation: 12, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F011'] },
    { id: 'D11-G02', displayName: 'Nguyễn Thị Toán', gender: 2, generation: 12, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F011'] },
    { id: 'D12-001a', displayName: 'Nguyễn Duy Oong', gender: 1, generation: 12, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F012'] },
    { id: 'D12-001b', displayName: 'Nguyễn Duy Thấm', gender: 1, generation: 12, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F012'] },
    { id: 'D12-001', displayName: 'Nguyễn Duy Thâm', gender: 1, generation: 12, birthYear: 1890, deathYear: 1953, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F013'], parentFamilyIds: ['F012'] },
    { id: 'D12-G01', displayName: 'Nguyễn Thị Sửu', gender: 2, generation: 12, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F012'] },
    { id: 'D12-G02', displayName: 'Nguyễn Thị Tý', gender: 2, generation: 12, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F012'] },
    { id: 'D12-G03', displayName: 'Nguyễn Thị Cỏn', gender: 2, generation: 12, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F012'] },
    { id: 'D12-002', displayName: 'Nguyễn Duy Hoạt', gender: 1, generation: 12, birthYear: 1908, deathYear: 1932, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F014'], parentFamilyIds: ['F012'] },
    { id: 'S_D12-001', displayName: 'Lương Thị Tiệp', gender: 2, generation: 12, birthYear: 1892, deathYear: 1983, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D12-002', displayName: 'Nguyễn Thị Xa', gender: 2, generation: 12, birthYear: 1964, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 13 ═══
    { id: 'D13-001', displayName: 'Nguyễn Duy Thiển', gender: 1, generation: 13, birthYear: 1915, deathYear: 1983, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F015'], parentFamilyIds: ['F013'] },
    { id: 'D13-002', displayName: 'Nguyễn Thị Điềm', gender: 2, generation: 13, birthYear: 1919, deathYear: 2003, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F013'] },
    { id: 'D13-003', displayName: 'Nguyễn Duy Xung', gender: 1, generation: 13, birthYear: 1921, deathYear: 2004, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F016'], parentFamilyIds: ['F013'] },
    { id: 'D13-004', displayName: 'Nguyễn Duy Cảng', gender: 1, generation: 13, birthYear: 1924, deathYear: 1946, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F013'] },
    { id: 'D13-005', displayName: 'Nguyễn Duy Đỗng', gender: 1, generation: 13, birthYear: 1928, deathYear: 1971, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F017'], parentFamilyIds: ['F013'] },
    { id: 'D13-006', displayName: 'Nguyễn Thị Én', gender: 2, generation: 13, birthYear: 1930, deathYear: 2018, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F013'] },
    { id: 'D13-007', displayName: 'Nguyễn Duy Bàng', gender: 1, generation: 13, birthYear: 1933, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F018'], parentFamilyIds: ['F013'] },
    { id: 'D13-008', displayName: 'Nguyễn Duy Luân', gender: 1, generation: 13, birthYear: 1927, deathYear: 2001, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F019'], parentFamilyIds: ['F014'] },
    { id: 'D13-009', displayName: 'Nguyễn Duy Luận', gender: 1, generation: 13, birthYear: 1930, deathYear: 1951, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F020'], parentFamilyIds: ['F014'] },
    { id: 'S_D13-001', displayName: 'Nguyễn Thị Thươm', gender: 2, generation: 13, birthYear: 1919, deathYear: 1995, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D13-003', displayName: 'Trần Thị Hoan', gender: 2, generation: 13, birthYear: 1922, deathYear: 2025, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D13-005', displayName: 'Nguyễn Thị Nhàn', gender: 2, generation: 13, birthYear: 1925, deathYear: 2017, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D13-007', displayName: 'Nguyễn Thị Cúc', gender: 2, generation: 13, birthYear: 1936, deathYear: 1998, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D13-008', displayName: 'Đỗ Thị Bẩy', gender: 2, generation: 13, birthYear: 2010, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D13-009', displayName: 'Đỗ Thị Nhãn', gender: 2, generation: 13, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 14 ═══
    { id: 'D14-001', displayName: 'Nguyễn Thị Gái', gender: 2, generation: 14, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F015'] },
    { id: 'D14-002', displayName: 'Nguyễn Duy Lẫm', gender: 1, generation: 14, birthYear: 1940, deathYear: 2018, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F021'], parentFamilyIds: ['F015'] },
    { id: 'D14-003', displayName: 'Nguyễn Duy Lãm', gender: 1, generation: 14, birthYear: 1945, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F022'], parentFamilyIds: ['F015'] },
    { id: 'D14-004', displayName: 'Nguyễn Thị Loan', gender: 2, generation: 14, birthYear: 1958, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F023'], parentFamilyIds: ['F015'] },
    { id: 'D14-005', displayName: 'Nguyễn Duy Lương', gender: 1, generation: 14, birthYear: 1961, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F024'], parentFamilyIds: ['F015'] },
    { id: 'D14-006', displayName: 'Nguyễn Thị Dung', gender: 2, generation: 14, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F016'] },
    { id: 'D14-007', displayName: 'Nguyễn Duy Chuyên', gender: 1, generation: 14, birthYear: 1945, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F025'], parentFamilyIds: ['F016'] },
    { id: 'D14-008', displayName: 'Nguyễn Duy Chung', gender: 1, generation: 14, birthYear: 1948, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F026'], parentFamilyIds: ['F016'] },
    { id: 'D14-009', displayName: 'Nguyễn Thị Thành', gender: 2, generation: 14, birthYear: 1954, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F016'] },
    { id: 'D14-010', displayName: 'Nguyễn Thị Chính', gender: 2, generation: 14, birthYear: 1958, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F016'] },
    { id: 'D14-011', displayName: 'Nguyễn Duy Dũng', gender: 1, generation: 14, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F017'] },
    { id: 'D14-012', displayName: 'Nguyễn Duy Quỳnh', gender: 1, generation: 14, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F017'] },
    { id: 'D14-013', displayName: 'Nguyễn Duy Đông', gender: 1, generation: 14, birthYear: 1957, deathYear: 2018, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F027'], parentFamilyIds: ['F017'] },
    { id: 'D14-014', displayName: 'Nguyễn Thị Phương', gender: 2, generation: 14, birthYear: 1959, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F017'] },
    { id: 'D14-015', displayName: 'Nguyễn Thị Hồng', gender: 2, generation: 14, birthYear: 1967, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F017'] },
    { id: 'D14-016', displayName: 'Nguyễn Thị Huyền', gender: 2, generation: 14, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F018'] },
    { id: 'D14-017', displayName: 'Nguyễn Duy Minh', gender: 1, generation: 14, birthYear: 1961, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F028'], parentFamilyIds: ['F018'] },
    { id: 'D14-018', displayName: 'Nguyễn Thị Hồng Vân', gender: 2, generation: 14, birthYear: 1964, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F018'] },
    { id: 'D14-019', displayName: 'Nguyễn Thị Minh Nguyệt', gender: 2, generation: 14, birthYear: 1968, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F018'] },
    { id: 'D14-020', displayName: 'Nguyễn Thị Nho', gender: 2, generation: 14, birthYear: 1952, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-021', displayName: 'Nguyễn Duy Quân', gender: 1, generation: 14, birthYear: 1954, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F029'], parentFamilyIds: ['F019'] },
    { id: 'D14-022', displayName: 'Nguyễn Duy Đỏ', gender: 1, generation: 14, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-023', displayName: 'Nguyễn Thị Mâu', gender: 2, generation: 14, birthYear: 1956, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-024', displayName: 'Nguyễn Thị Ngoan', gender: 2, generation: 14, birthYear: 1958, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-025', displayName: 'Nguyễn Thị Ngoãn', gender: 2, generation: 14, birthYear: 1958, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-026', displayName: 'Nguyễn Thị Nhâm', gender: 2, generation: 14, birthYear: 1961, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-027', displayName: 'Nguyễn Duy Phi', gender: 1, generation: 14, birthYear: 1963, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-028', displayName: 'Nguyễn Thị Quý', gender: 2, generation: 14, birthYear: 1965, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-029', displayName: 'Nguyễn Thị Tốt', gender: 2, generation: 14, birthYear: 1967, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-030', displayName: 'Nguyễn Thị Hồng Lĩnh', gender: 2, generation: 14, birthYear: 1969, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-031', displayName: 'Nguyễn Thị Khánh Dư', gender: 2, generation: 14, birthYear: 1971, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F019'] },
    { id: 'D14-032', displayName: 'Nguyễn Thị Lê', gender: 2, generation: 14, birthYear: 1950, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F020'] },
    { id: 'D14-033', displayName: 'Nguyễn Duy Đan', gender: 1, generation: 14, birthYear: 1951, deathYear: 1960, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F020'] },
    { id: 'S_D14-002', displayName: 'Bùi Thị Tân Thư', gender: 2, generation: 14, birthYear: 1943, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-003', displayName: 'Nguyễn Thị Kim Loan', gender: 2, generation: 14, birthYear: 1950, deathYear: 2022, isLiving: false, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-004', displayName: 'NguyễnQuang Minh', gender: 2, generation: 14, birthYear: 1956, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-005', displayName: 'Nguyễn Thị Thu Thủy', gender: 2, generation: 14, birthYear: 1971, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-007', displayName: 'Lê Thị Thơ', gender: 2, generation: 14, birthYear: 1952, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-008', displayName: 'Ninh Thị Ty', gender: 2, generation: 14, birthYear: 1954, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-013', displayName: 'Nguyễn Thị Loan', gender: 2, generation: 14, birthYear: 1969, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-017', displayName: 'Nguyễn Thị Hiền', gender: 2, generation: 14, birthYear: 1968, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    { id: 'S_D14-021', displayName: 'Đặng Thị Phương', gender: 2, generation: 14, birthYear: 1954, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: [], parentFamilyIds: [] },
    // ═══ Đời 15 ═══
    { id: 'D15-001', displayName: 'Nguyễn Thanh Giang', gender: 2, generation: 15, birthYear: 1974, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F021'] },
    { id: 'D15-002', displayName: 'Nguyễn Duy Việt Phong', gender: 1, generation: 15, birthYear: 1976, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F021'] },
    { id: 'D15-003', displayName: 'Nguyễn Duy Hoàng', gender: 1, generation: 15, birthYear: 1983, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F031'], parentFamilyIds: ['F022'] },
    { id: 'D15-004', displayName: 'Nguyễn Duy Hải', gender: 1, generation: 15, birthYear: 1991, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: ['F030'], parentFamilyIds: ['F022'] },
    { id: 'D15-005', displayName: 'Nguyễn Thị Phương Liên', gender: 2, generation: 15, birthYear: 1987, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F023'] },
    { id: 'D15-006', displayName: 'Nguyễn Duy Thành', gender: 1, generation: 15, birthYear: 1993, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F024'] },
    { id: 'D15-007', displayName: 'Nguyễn Duy Đức', gender: 1, generation: 15, birthYear: 2001, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F024'] },
    { id: 'D15-008', displayName: 'Nguyễn Duy Hoàng Hải', gender: 1, generation: 15, birthYear: 1978, deathYear: 2004, isLiving: false, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F025'] },
    { id: 'D15-009', displayName: 'Nguyễn Thị Hoàng Yến', gender: 2, generation: 15, birthYear: 1982, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F025'] },
    { id: 'D15-010', displayName: 'Nguyễn Duy Ninh', gender: 1, generation: 15, birthYear: 1981, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F026'] },
    { id: 'D15-011', displayName: 'Nguyễn Thị Hải Yến', gender: 2, generation: 15, birthYear: 1990, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F026'] },
    { id: 'D15-012', displayName: 'Nguyễn Thị Thùy Linh', gender: 2, generation: 15, birthYear: 1995, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F027'] },
    { id: 'D15-013', displayName: 'Nguyễn Thị Hà Chi', gender: 2, generation: 15, birthYear: 1999, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F027'] },
    { id: 'D15-014', displayName: 'Nguyễn Duy Bình', gender: 1, generation: 15, birthYear: 1998, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F028'] },
    { id: 'D15-015', displayName: 'Nguyễn Thị Giang', gender: 2, generation: 15, birthYear: 1976, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F029'] },
    { id: 'D15-016', displayName: 'Nguyễn Duy Công', gender: 1, generation: 15, birthYear: 1980, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F029'] },
    { id: 'D15-017', displayName: 'Nguyễn Thị Dung', gender: 2, generation: 15, birthYear: 1986, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F029'] },
    { id: 'S_D15-003', displayName: 'Nguyễn Thùy Linh', gender: 2, generation: 15, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: ['F031'], parentFamilyIds: [] },
    { id: 'S_D15-004', displayName: 'Nguyễn Hoài Anh', gender: 2, generation: 15, isLiving: true, isPrivacyFiltered: false, isPatrilineal: false, familyIds: ['F030'], parentFamilyIds: [] },
    // ═══ Đời 16 ═══
    { id: 'D16-001', displayName: 'Nguyễn Duy Hoàng Minh', gender: 1, generation: 16, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F030'] },
    { id: 'D16-002', displayName: 'Nguyễn Duy Hà An', gender: 1, generation: 16, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F031'] },
    { id: 'D16-003', displayName: 'Nguyễn Duy Khải Anh', gender: 1, generation: 16, isLiving: true, isPrivacyFiltered: false, isPatrilineal: true, familyIds: [], parentFamilyIds: ['F031'] },
];

export const MOCK_FAMILIES: TreeFamily[] = [
    { id: 'F001', fatherId: 'D01-001', motherId: 'S_D01-001', childIds: ['D02-001', 'D02-002', 'D02-003'] },
    { id: 'F002', fatherId: 'D02-003', childIds: ['D03-001'] },
    { id: 'F003', fatherId: 'D03-001', motherId: 'S_D03-001', childIds: ['D04-001'] },
    { id: 'F004', fatherId: 'D04-001', childIds: ['D05-001'] },
    { id: 'F005', fatherId: 'D05-001', motherId: 'S_D05-001', childIds: ['D06-001', 'D06-002', 'D06-003'] },
    { id: 'F006', fatherId: 'D06-001', motherId: 'S_D06-001', childIds: ['D07-001'] },
    { id: 'F007', fatherId: 'D07-001', motherId: 'S_D07-001', childIds: ['D08-001', 'D08-002'] },
    { id: 'F008', fatherId: 'D08-001', motherId: 'S_D08-001', childIds: ['D09-001', 'D09-002', 'D09-003'] },
    { id: 'F009', fatherId: 'D09-002', motherId: 'S_D09-002', childIds: ['D10-001', 'D10-002', 'D10-003'] },
    { id: 'F010', fatherId: 'D10-003', motherId: 'S_D10-003', childIds: ['D10-004', 'D11-001', 'D11-002'] },
    { id: 'F011', fatherId: 'D11-001', motherId: 'S_D11-001', childIds: ['D12-T01', 'D11-G01', 'D11-G02'] },
    { id: 'F012', fatherId: 'D11-002', motherId: 'S_D11-002', childIds: ['D12-001a', 'D12-001b', 'D12-001', 'D12-G01', 'D12-G02', 'D12-G03', 'D12-002'] },
    { id: 'F013', fatherId: 'D12-001', motherId: 'S_D12-001', childIds: ['D13-001', 'D13-002', 'D13-003', 'D13-004', 'D13-005', 'D13-006', 'D13-007'] },
    { id: 'F014', fatherId: 'D12-002', motherId: 'S_D12-002', childIds: ['D13-008', 'D13-009'] },
    { id: 'F015', fatherId: 'D13-001', motherId: 'S_D13-001', childIds: ['D14-001', 'D14-002', 'D14-003', 'D14-004', 'D14-005'] },
    { id: 'F016', fatherId: 'D13-003', motherId: 'S_D13-003', childIds: ['D14-006', 'D14-007', 'D14-008', 'D14-009', 'D14-010'] },
    { id: 'F017', fatherId: 'D13-005', motherId: 'S_D13-005', childIds: ['D14-011', 'D14-012', 'D14-013', 'D14-014', 'D14-015'] },
    { id: 'F018', fatherId: 'D13-007', motherId: 'S_D13-007', childIds: ['D14-016', 'D14-017', 'D14-018', 'D14-019'] },
    { id: 'F019', fatherId: 'D13-008', motherId: 'S_D13-008', childIds: ['D14-020', 'D14-021', 'D14-022', 'D14-023', 'D14-024', 'D14-025', 'D14-026', 'D14-027', 'D14-028', 'D14-029', 'D14-030', 'D14-031'] },
    { id: 'F020', fatherId: 'D13-009', motherId: 'S_D13-009', childIds: ['D14-032', 'D14-033'] },
    { id: 'F021', fatherId: 'D14-002', motherId: 'S_D14-002', childIds: ['D15-001', 'D15-002'] },
    { id: 'F022', fatherId: 'D14-003', motherId: 'S_D14-003', childIds: ['D15-003', 'D15-004'] },
    { id: 'F023', fatherId: 'D14-004', motherId: 'S_D14-004', childIds: ['D15-005'] },
    { id: 'F024', fatherId: 'D14-005', motherId: 'S_D14-005', childIds: ['D15-006', 'D15-007'] },
    { id: 'F025', fatherId: 'D14-007', motherId: 'S_D14-007', childIds: ['D15-008', 'D15-009'] },
    { id: 'F026', fatherId: 'D14-008', motherId: 'S_D14-008', childIds: ['D15-010', 'D15-011'] },
    { id: 'F027', fatherId: 'D14-013', motherId: 'S_D14-013', childIds: ['D15-012', 'D15-013'] },
    { id: 'F028', fatherId: 'D14-017', motherId: 'S_D14-017', childIds: ['D15-014'] },
    { id: 'F029', fatherId: 'D14-021', motherId: 'S_D14-021', childIds: ['D15-015', 'D15-016', 'D15-017'] },
    { id: 'F030', fatherId: 'D15-004', motherId: 'S_D15-004', childIds: ['D16-001'] },
    { id: 'F031', fatherId: 'D15-003', motherId: 'S_D15-003', childIds: ['D16-002', 'D16-003'] },
];

export interface MemorialEvent {
    personId: string;
    personName: string;
    generation: number;
    day: number;
    month: number;
    deathYear?: number;
    isLunar: boolean;
}

export const MOCK_MEMORIALS: MemorialEvent[] = [
    { personId: 'D05-001', personName: 'Nguyễn Duy Điển', generation: 5, day: 5, month: 1, deathYear: 1711, isLunar: true },
    { personId: 'D04-001', personName: 'Nguyễn Duy Khối', generation: 4, day: 8, month: 1, isLunar: true },
    { personId: 'D13-009', personName: 'Nguyễn Duy Luận', generation: 13, day: 26, month: 1, deathYear: 1951, isLunar: true },
    { personId: 'D07-001', personName: 'Nguyễn Duy Vẽ', generation: 7, day: 17, month: 2, deathYear: 1788, isLunar: true },
    { personId: 'S_D13-008', personName: 'Đỗ Thị Bẩy', generation: 13, day: 7, month: 3, deathYear: 2010, isLunar: true },
    { personId: 'D13-008', personName: 'Nguyễn Duy Luân', generation: 13, day: 17, month: 3, deathYear: 2001, isLunar: true },
    { personId: 'D03-001', personName: 'Nguyễn Duy Hộ', generation: 3, day: 15, month: 5, isLunar: true },
    { personId: 'S_D11-002', personName: 'Phạm Thị Lượt', generation: 11, day: 20, month: 5, isLunar: true },
    { personId: 'D09-002', personName: 'Nguyễn Duy Nham', generation: 9, day: 3, month: 6, deathYear: 1862, isLunar: true },
    { personId: 'D12-T01', personName: 'Nguyễn Duy Tồm', generation: 12, day: 10, month: 6, isLunar: true },
    { personId: 'D13-003', personName: 'Nguyễn Duy Xung', generation: 13, day: 11, month: 6, deathYear: 2004, isLunar: true },
    { personId: 'D02-003', personName: 'Nguyễn Duy Trạch', generation: 2, day: 15, month: 6, isLunar: true },
    { personId: 'D14-013', personName: 'Nguyễn Duy Đông', generation: 14, day: 23, month: 6, deathYear: 2018, isLunar: true },
    { personId: 'D10-003', personName: 'Nguyễn Duy Khoan Giản', generation: 10, day: 28, month: 6, deathYear: 1868, isLunar: true },
    { personId: 'S_D12-001', personName: 'Lương Thị Tiệp', generation: 12, day: 28, month: 6, deathYear: 1983, isLunar: true },
    { personId: 'D14-002', personName: 'Nguyễn Duy Lẫm', generation: 14, day: 18, month: 7, deathYear: 2018, isLunar: true },
    { personId: 'S_D13-001', personName: 'Nguyễn Thị Thươm', generation: 13, day: 19, month: 7, deathYear: 1995, isLunar: true },
    { personId: 'D01-001', personName: 'Nguyễn Duy Hòa', generation: 1, day: 30, month: 7, deathYear: 1577, isLunar: true },
    { personId: 'D11-001', personName: 'Nguyễn Duy Khâm', generation: 11, day: 30, month: 7, isLunar: true },
    { personId: 'S_D13-007', personName: 'Nguyễn Thị Cúc', generation: 13, day: 24, month: 8, deathYear: 1998, isLunar: true },
    { personId: 'D13-001', personName: 'Nguyễn Duy Thiển', generation: 13, day: 2, month: 9, deathYear: 1983, isLunar: true },
    { personId: 'D13-005', personName: 'Nguyễn Duy Đỗng', generation: 13, day: 2, month: 9, deathYear: 1971, isLunar: true },
    { personId: 'D13-004', personName: 'Nguyễn Duy Cảng', generation: 13, day: 20, month: 9, deathYear: 1946, isLunar: true },
    { personId: 'D12-001', personName: 'Nguyễn Duy Thâm', generation: 12, day: 6, month: 10, deathYear: 1953, isLunar: true },
    { personId: 'D08-001', personName: 'Nguyễn Duy Hoán', generation: 8, day: 4, month: 11, deathYear: 1821, isLunar: true },
    { personId: 'S_D12-002', personName: 'Nguyễn Thị Xa', generation: 12, day: 7, month: 11, deathYear: 1964, isLunar: true },
    { personId: 'D11-002', personName: 'Nguyễn Duy Sảng', generation: 11, day: 11, month: 11, deathYear: 1921, isLunar: true },
    { personId: 'D15-008', personName: 'Nguyễn Duy Hoàng Hải', generation: 15, day: 16, month: 11, deathYear: 2004, isLunar: true },
    { personId: 'D12-002', personName: 'Nguyễn Duy Hoạt', generation: 12, day: 25, month: 11, deathYear: 1932, isLunar: true },
    { personId: 'S_D13-005', personName: 'Nguyễn Thị Nhàn', generation: 13, day: 7, month: 12, deathYear: 2017, isLunar: true },
    { personId: 'S_D11-001', personName: 'Nguyễn Thị Viễn', generation: 11, day: 28, month: 12, isLunar: true },
];

export function getMockTreeData() {
    return { people: MOCK_PEOPLE, families: MOCK_FAMILIES };
}
